config/routes.rb
Rails.application.routes.draw do
  get "about-us", to: "about#index", as: :about

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  delete "logout", to: "sessions#destroy"

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/, message:"debe ser una dirección de email válida" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def  index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def  index
       if session[:user_id]
        @user = User.find_by(id: session[:user_id])
        
       end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
def new
    @user = User.new
end

def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Cuenta creada con éxito"
    else
        render :new
    end
end

private

def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render partial: "shared/navbar" %>
  <div class="container">
  <%= render partial: "shared/flash"%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Bienvenido a calendario de tweets</h1>
</div>

<% if @user %>
Logged in as: <%= @user.email %>

 <%= button_to  "Logout", logout_path, method: :delete %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-warning mt-4" role="alert">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to  "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to  "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to  "About", about_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>